const articles = [

  { Title:"Gapping the difference",
    Authors:"Revati Deshpande and Sania Mahabaleshwarkar",
    path:"article1.jpg",
    Content:"The gender pay gap is the average difference between the remuneration for men and women who are working. It exists over all sectors and income classes. It is said that given the current situation, the gender pay gap will take at least 170 years to be completely eradicated."+
    "Historically, participation in sports has been discriminatory, favouring men over women because the sport has been viewed as an inappropriate field for women. Despite the fact that women's participation in sports has increased over time, many parts of the sport still have underlying gender prejudices."+
    "The wage disparity is one of the most striking features of bias, as women are paid significantly less in sports than males. The staggering pay gap between the highest-paid players in men's and women's cricket in India is an example of this: Smriti Mandhana is paid US$68,500 per year by the Board of Control for Cricket in India (BCCI), which is only 7% of Virat Kohli's annual income of US$952,000."+
    "Some reasons for the existence of the pay gap are:"+
    "The production of income is frequently claimed to justify the salary disparity in sports. The argument is that the returns generated by male players are higher than what women generate. A number of factors are taken into account when calculating the financial benefits of sports, including endorsements, sports merchandising, and ticket sales, among others. This, however, is based on viewership and fanbase, which are influenced by sports' androcentric nature."+
    "Due to societal constraints, women began participating in sports much later than men. As a result, women's sport has a lower 'entertainment value.' Men's sport, on the other hand, has always been supported, allowing it to grow into a global phenomenon and attracting more investment."+
    "Another justification for the pay disparity in sports is the physical differences between men and women. This argument claims that men should be paid more because they are stronger and can perform better in sports than women. Men play five sets per match in professional tennis, while women play three sets per match, based on the assumption that women are physically weaker than men. Despite women's demonstrated willingness and ability to play five sets, decision-makers (mostly men) believed that if women played five sets, the game's quality would suffer."+
    "While it is true that men could have greater strength and speed than women, these are only two physical characteristics that matter in sports, and they cannot be used to justify paying men more than women. Women may be better at other aspects such as balance and flexibility, but this does not imply that women are paid more in sports that require flexibility and balance."+
    "The persistent pay gap in the sports industry is also due to a lack of female representation in sports governance structures. Although female representation in some governance structures has improved, this is a recent development. Furthermore, most governing bodies still need to make a stronger push to increase female participation."+
     
    "The conversation over pay inequality has even reached the heights of the entertainment industry. Top-tier actresses struggle just to get what they deserve. In 2017’s Forbes' Celebrity 100 list of the world's highest-earning entertainers, no Bollywood actress cracked the list. Top Bollywood actors make at least five times as much as top actresses, and some directors are happy to keep it that way. In 2003, director Karan Johar fired A-list actress Kareena Kapoor from the film Kal Ho Na Ho after she demanded the same amount of money as the lead actor Shah Rukh Khan."+
    "One explanation for the disparity is the box office. According to Chopra in an interview with BBC, films with a male lead earn $40 million at the box office, while films with a female lead earn less than a quarter. The disparity will end when women-centred films become hits, +she said. Onscreen, shaking off the weak stereotypes of subservient girlfriends, sisters, and mothers will also help. Some films have already begun to do so. And it's worked out well."+
"Over the last few years, female-led films like Ranaut's Queen, Vidya Balan's The Dirty Picture, Chopra's Mary Kom, Padukone's Piku, and Bajirao Mastani have all surpassed the $15 million gross earnings mark, which is considered a hit in Bollywood."+
"Institutional efforts have begun, and they will play an important role in laying the groundwork for long-term positive changes to close the gender pay gap. In May 2022, the U.S. Soccer Federation announced that players for the men's and women's national teams would get equal compensation."+
" However, to ensure that these industries become more equitable for all, regardless of gender, the process of bringing about these changes must be faster and more consistent around the world."+
"Women globally earn 37% less than that men."+
"Iceland has the least gap; with a 0.86 the index and Yemen has an exorbitant index of 0.50"+
"In India, the gender pay gap is 62.5% making India fall 28 places and hit the 140th rank in the World Economic Forum (WEF). During the pandemic times, many women were fired. After eight months of the lockdown, 13% fewer women than a year ago were hired or looking for jobs. This data primarily represents the tertiary sector. But women in the labour industry also suffer. Women labourers are considered to have lesser skill levels on entry, and seek very less employment opportunities, resulting in less pay than the male labourers."+
"The World banknotes that equal pay for an equal value of work is mandated only in fewer than half of the world. There are certain roles handed out to each gender. History has seen society play along with the same rule book for years and years. But, girls are trying to fulfil their dreams in a real sense and not just in movies or stories. Yes, it might take these ladies 170 years to earn as equal as the men. We might not be alive then, but for sure as a society people will celebrate this day and these numbers, biases, and prejudices will change and bring a smile to each and every beautiful face."  

  },
  {
    Title: "ANTIQUITY OF PRIDE",
    Authors:"Revati Deshpande and Reva Srivastava",
    Content:
      "Love is too beautiful to be hidden in the closet" +
      "Even though same-sex marriages are opposed by many as they believe that this concept is" +
      "oxymoronic because marriage, they say, must involve a man and a woman only; its supporters" +
      "celebrate it as a sign of progress and we at Girl-Up believe that loving someone should never" +
      "mean having to live in fear" +
      "It all began when Jack Baker and James McConnell applied for a marriage license in the USA in" +
      "1970. Although it was turned down by the Supreme Court in 1972, it gave rise to a worldwide" +
      "awareness and helped other same-sex couples come out and display their affection for each" +
      "other publicly. Later, the District of Columbia law allowed unmarried couples, irrespective of" +
      "their gender, to register as domestic partners. This marked a turning point in the US history as" +
      "Columbia was the first city to legalise same-sex couples. Even then, the US saw a continuous " +
      "ban of these marriages by its Presidents including Bill Clinton and George Bush until Barack " +
      "Obama became the first president to endorse gay marriages in 2012. Since then, people " +
      "became more open and acceptable to this and same-sex marriage was finally legalized " +
      "nationwide in 2015." +
      "Similarly, the history of many African and Asian cultures includes same-sex and transgender " +
      "marriages. But examples of formal religious ceremonies in which two men who love each other " +
      "are solemnly wedded together can be found across Europe, throughout Classical Antiquity " +
      "(between 8th century BC and 6th century AD) and until the end of the middle age. It is also " +
      "rumoured that during the Italian Renaissance (14th to 17th century), there were instances where " +
      "men were fined (and in extreme cases, burned) for living with another man “by keeping him as " +
      "his wife and in place of a wife”." +
      "Therefore, they did not tend to live together, but passionate friendships and love between men " +
      "took a lot of different forms. From Henry James and Oscar Wilde’s relationship to the passion of " +
      "David and Jonathan (of Achilles and Patroclus), countless popular ballads began writing about " +
      "gay couples." +
      "Thus it is clear that homosexual relationships in the past were not the same as they are in the" +
      "present. Although this does not imply that gay couples and the LGBTQ+ community don’t face " +
      "any hardships in the modern world." +
      "These struggles saw a number of faces in the court of law all over the world. These laws took " +
      "turns as the road took them, but there came a moment where roads had to be laid according to " +
      "what the LGBTQ+ community wanted. This paved the way for the very colourful and bright " +
      "‘Pride Parades’. Pride is an act of resistance. Pride parades’ inception was directly related to the" +
      "social and political unrests against the LGBTQ+ community. In the 1960s, raiding gay bars and " +
      "arresting the patrons in it, was a regular routine. On the 27th of June 1970, Stonewall Inn, a gay" +
      "bar at downtown, Manhattan was raided as a part of police patrolling. But this time every queer " +
      "in there stood up and fought back. This wasn’t a coloured flag hoisted, dance and music parade " +
      "though, but an ignition of the beautiful rainbow coloured flame that we see today. This flame " +
      "was kept lit by big bold pillars such as, transwomen Marsha P, Johnson’s Sylvia and Miss Major " +
      "in the first pride event in 1970, the Cristopher street liberation day march to commemorate the" +
      "agitation at the Stonewall Inn in 1965. And came into being the Pride month." +
      "Then in 1978, the first openly gay artist Gilbert Baker designed the first rainbow flag. He was " +
      "insisted by Harvey Milk, the first openly gay elected U.S. official who stated that flags are a" +
      "strong symbol of pride. Baker saw the rainbow as the sole flag of nature. So he adopted 8 " +
      "colours for the flag, each one having an inherent meaning. Hot pink for sex, red for life, orange " +
      "for healing, yellow for sunlight, green for nature, turquoise for art, indigo for harmony and violet" +
      "for spirit. These colours brought in a new psyche and energy. " +
      "The LGBTQ+ community has been within us for a long time. We knew they were there, and saw" +
      "them everyday. Some supported, some disagreed. We were really proud when we supported " +
      "THEM. The only problem is us differentiating the community. Parting them from the mainstream." +
      "Yes, surely they are not some conventional human being, but strive to become one. And that’s " +
      "what we all should support. Bringing us and them together. Making one human community " +
      "which will cherish everyone’s choices irrespective of what they are. Because a heart always" +
      "makes the purest of choices and never lies. For this we all should stand up and start " +
      "normalising the different... ",
    path: "art1.png",
  },
  {
    Title: "FORCES AGAINST SAME SEX MARRIAGES",
    Authors:"Sania Mahabaleshwarkar and Harleen Kaur Grewal",
    Content:
      "As the world has developed over the years, globalization and technology have enabled progress in the population's mindset and beliefs. With this, people have also found freedom and societal acceptance in terms of sexual and gender orientation. People of all ages come out and explore their identities and aren't rejected in many societies. In some countries, legalization, or even displays of LGBT love is celebrated with rainbow-coloured merchandise and cheers. In other countries, it is a topic that is considered to be taboo, something which is to be frowned upon." +
      "While we have taken strides from where we once were, the LGBTQ+ community is subject to deep-rooted prejudice in the form of discrimination, intolerance, harassment, and violence even today. Some of the factors that may reinforce homophobia on a larger scale are the moral, religious, and political beliefs of a dominant group. In some countries, homosexuality is illegal and punishable by fines, imprisonment, life imprisonment, and even the death penalty. The fact that the Universal Declaration for Human Rights, drafted in 1948, does not specifically include sexual orientation allows some people to consider LGBT rights debatable. Now more and more people are openly expressing their sexual orientation, and organizing and demanding their rights. Because of the work of these groups and their allies, acceptance of LGBT rights around the world is growing, and governments in certain countries are beginning to legislate in favour of LGBT rights and anti-discrimination laws. Influential international human rights organizations such as Amnesty International and Human Rights Watch continue to run effective campaigns" +
      "But this wasn’t always the case, especially if we consider Muslim communities. In the 13th and 14th centuries, poets like Rumi and Hafiz wrote lewd verses with relative openness. In contrast, the modern Middle East has a very different stance on this topic. According to the survey taken by Pew Research Centre in 2013, most of the population thinks that homosexuals should be rejected from society: 97% in Jordan, 95% in Egypt, and 80% in Lebanon. In some countries, homosexuality is illegal and punishable by fines, imprisonment, life imprisonment and even the death penalty." +
      "Regardless of Sunni or Shia, most Muslims do have very negative attitudes toward people of LGBT. To the traditionalists, the Quran is clear about homosexuality, and there is no tolerance for debating the context or semantics. According to Mission Islam, an online network on varying Islamic teachings, every major Islamic school of thought considers sex between two men to be sinful and unlawful. Some schools of thought believe it merits severe physical punishment, including stoning to death." +
      "Others would sentence it with imprisonment or banishment from the state. Today, most governments that follow Islamic law defer on the punishment used for offenders. But there have been cases where men convicted of having gay sex have been killed. According to the International Lesbian and Gay Association, only eight predominately Muslim countries, as of 2011, retain capital punishment for homosexual behaviour: Saudi Arabia, Iran, Yemen, Qatar, Sudan, Somalia, Nigeria, and Mauritania" +
      "In Iraq, where same-sex activity is technically legal, the breakdown of order since 2003 has allowed Islamist militias and vigilantes to impose their idea of justice. Groups such as Islamic State have become notorious for gruesomely murdering people suspected of being gay by throwing them off buildings and stoning them to death" +
      "LGBT Muslims living in the United States do not typically experience this sort of physical punishment though they often face verbal persecution and social exclusion from traditional Muslim communities" +
      "Disparate sources attest to the commonality of homosexuality or homosexual practices in the Middle East in both pre-Islamic and Islamic times, the prohibition of the Quran and certain hadith against such practices, the prevalence of homoerotic themes in much of classical Arabic and Persian poetry, the extent to which the 17th, 18th and 19th-century European travellers in the Orient were impresses or shocked by its exhibiting what appeared to be a widespread, relatively public homosexual culture, and possible links between homosexuality and the origins and structure of Ottoman and Egyptian Mamluk military societies. As for more orthodox Western scholarship, history has tended to accord homosexuality an occasional and often dispositive footnote; ethnography and, more surprisingly, contemporary feminist studies treat homosexuality, if at all, dismissively - as marginal, linked to arcane initiation rituals or adolescent (hence, temporary) sexual practices in a context of sexual segregation. There are several explanations as to why ho9mosexuality is a closed subject of inquiry. The long-standing Western culture Western cultural antipathy towards homosexuality is mirrored in the Arab world by both the lack of public discourse of sexuality and a cultural taboo against homosexuality which, at present, appears to have achieved official status. Moreover, what might be described as structural myopia of predominantly heterosexual scholarship is entirely congruent with the orientalist epistemological legacy of treating texts, like the quranic prohibitions, as constitutive social realities. Social history, with its concern for the role and place in the history of minorities, ordinary people and their daily lives and perceptions, did not emerge as a corrective to traditional, political, institutional, and military history until the late 1960s" +
      "Homosexuality has indeed been commonplace, generally involving asymmetrical relations that reflect age, status, or class differences between partners and have involved variations along class lines. There is little evidence of modern homosexuality in the modern urban Middle East, although there have been reports of gay rights demonstrations in Kuwait and underground organizations in large cities such as Cairo" +
      "Sex in Islam is recognized as natural, necessary, and pleasurable, whether or not engaged in for procreative purposes. Sexual intercourse is considered lawful only when a man and woman are involved in the act which for women means that they are permitted to sexual activities only with their husbands. Sodomy between members of the same sex and Zina between men and women are strongly prohibited, and since homosexuality, more properly considered under the umbrella of sodomy by the law that prohibits homosexuality, existed in pre-Islamic times, it is mentioned in the Quran, wherein, having drawn upon the biblical story of Lot and his people, homosexuality is condemned and punishable with no concrete punishment to bear conviction. As mentioned earlier, a majority deem public humiliation through stoning as a punishment for both sodomy and adultery, while a minority advocate death sentences as repercussions for said offences. In Iran, lavat is a capital offence and has often resulted in frequent executions. Saudi Arabia, Sudan, Yemen, and Mauritania, sodomy is punishable by death. Algeria, Bahrain, Kuwait, Lebanon, Libya, Morocco, Oman, Qatar, Somalia, Tunisia, and Syria hand out imprisonment sentences which could last up to 10 years. Egypt pushed homosexuality as an offence under debauchery. Although these laws may not actively seek out same-sex couples for vigorous enforcement of punishment, they nod towards the active disapproval of the fundamental right of a human being to love another human being regardless of their gender identity or sex. Such hostility often gives rise to the ruination of a person's life. Many give in to societal pressures and sign the contract to an ill-suited marriage. Some bite the bullet and decide to come out, resulting in ostracization from their families or being cast out; the worst is when the families start to seek out cures through futile conversion therapy"+
      "It is since 2002 that activism has gained the light of day through Palestinian groups such as Aswat and al-Qaws. Magazines like My Kali fight such inhumane treatment by addressing homophobia and transphobia to empower the youth to defy mainstream gender binaries in the Arab world and have been actively publishing since 2007. Social Media has contributed greatly to encouraging activism even at individual levels where advocates for the basic human rights of the LGBTQIA community speak out against irrational stigmas and dogmas" +
      "In a world of 195 countries, only 29 allow same-sex couples to access marriage rights. The 18 Middle Eastern countries are part of the 72 countries where homosexuality is illegal. The reasons behind the criminalisation of homosexuality in these countries are unknown, but, there is one reason that supports the beliefs of all those who advocate same-sex marriage: equal human rights wherein every individual enjoys the same rights as any other, regardless of their class, gender, religion, or sexual orientation, wherein an individual's welfare and happiness is above a law written on paper or religion created by man, where love has no gender or sex, where love is love.",
      path:"art2.jpg"
  },
  {
      Title: "PV SINDHU – THE NATION’S PRIDE",
      Authors:"Dea Parakh and Shakti Tripathi ",
      Content:"Pusarla Venkata Sindhu, an Olympic medallist, is more than just a pioneer for Indian athletes, having paved a way for aspiring women all over the country. An ace shuttler – she was born to a pair of sportsmen on 5th July, 1995. Her mother P Vijaya, is a national level volleyball player, just like her father PV Raman, indicating that sport was clearly her calling since childhood."+
      "Though obvious expectation would have been for her to follow her parents’ footsteps in volleyball, she went on to become an International badminton sensation. Introduced to the sport at the age of eight, she become a student at Gopichand Badminton Academy under coach Pullela Gopichand."+
      "Her potential and talent were evident from her early performances, but she attained major recognition on coming 5th in the Servo All India championship for the under 10 category. Her upward trajectory continued when she received a gold medal in the 51st National School Games."+
      "Internationally, she debuted at the Sub-Junior Asian Badminton Championship in 2009, where she was awarded a bronze. At the International Badminton Challenge held in Iran in 2010, she became the runner up, which was followed by countless other silvers. “Silver Sindhu” – was the title given to her. At the tender age of 17, she won the Asian junior Championships, becoming a global badminton whiz. She bagged her first Grand Prix in 2013 and was awarded the Arjuna Award the following year – one of the highest honours for any sportsperson in India."+
      "However, the biggest moment in Sindhu’s career came in the year 2016, when she went on to become the youngest and the first female athlete from India to win a silver medal at the Rio Olympics. She lost to then World No.1 Carolina Marin of Spain on 19th August 2016 and was graced with India’s fourth highest civilian award, The Padma Shri, later that year."+
      "In 2017, Sindhu won the Indian Open Super Series and later added a silver at the BWF World Championships. After reaching the final of the 2018 World Championships, she became the first shuttler in the world to reach the finals of three major successive events. She also rose to a career high ranking of no.2 the same year. However, the Gold medal remained elusive and she had to settle for a silver each time."+
      "On 16th December 2018, Sindhu made history by becoming the first Indian to win the season ending BWF World Tour Finals Tournament in China."+
      "Under the tutelage of Coach Pullela Gopichand, Sindhu is now no.7 in the world. With earnings of $8.5 million, she was ranked 7th in Forbes list of Highest-Paid Female Athletes in 2018, and was also the only Indian mentioned in the list."+
      "Her story is an inspiration to all the young Indian sportswomen today. She has filled our hearts with pride over the past decade with countless achievements though her dedication and hard work and has an incredibly honourable position in the history of Indian Sports.",
      path:"art3.jpeg"
      
  },
  {
   Title:"Magnificent Mary And The Story Of Her Challenges",
   Authors:"Kuhu Kulkarni and Tanvi Panse",
   Content:"Mary Kom is now a household name in India, but this success did not come easy for her. She made her world debut at the first Women Boxing Championship in Pennsylvania, USA, at the mere age of 18, and getting there from Kangathei, a village in Manipur was not easy. Growing up, she was told that sports are not for girls. She used to play with the boys in her village, and even after a few years in boxing, she often struggled to find female boxers to practice with."+
   "Initially, her family was not very keen on her pursuing boxing; they were worried she wouldn’t get a good marriage proposal if she bruised her face in the sport. Moreover, boxing wasn’t a trendy sport either, and those who knew about it held the conception that it is a sport for men, not women. Many people laughed at her when she said she wanted to take up boxing, and she had to face all these challenges before she even debuted and had to make herself believe that she belonged to boxing. She says every medal she’s won is a story of a difficult struggle, and we don’t doubt that."+
   "Mary had to walk miles to practice in her early days of boxing. Even as a state and national level player, she had to travel in sleeper class with no facilities. Yet, today when she looks back at those times, she says it’s okay and talks about how she wouldn’t have been where she is today if it weren’t for the challenges she faced."+
   "Even after establishing herself in the sport, the challenges did not cease for Mary. Once she got married in 2005, people began doubting if and how she would continue boxing because women do not often continue in sports after marriage, and especially a sport like boxing that’s so physical and intensive. Then again, when she became a mother for the first time in 2007, things got more complicated. This time, even her father had his doubts about Mary returning to boxing. Her son was facing severe medical conditions, but her husband encouraged her to continue boxing. After a short hiatus, Mary returned to boxing and proved to the world that getting married and having children does not stop her. She went on to win a silver medal at the 2008 Asian Women’s Boxing Championship in India and a gold medal in 2009 at the Asian Indoor Games in Vietnam after her hiatus. It definitely must not have been easy, but she never gave up."+
   "Mary’s story is one of a kind. She did not have any facilities, significantly less support, and many challenges in her way. She overcame gender bias, poverty, and we cannot imagine the amount of dedication and strength it must have required, both physically and mentally, to become so successful in a sport as intense as boxing."+
   "Today, apart from being a role model, Mary Kom is the only female to become World Amateur Boxing Champion six times, the only female boxer to have won a medal in all of the seven World Championships, the only boxer, male and female, to win eight World Championship medals!",
   path:"art4.jpg"

  },
  {
     Title:"The cruel case of domestic violence",
     Authors:"Tanvi Panse and Annanya Srivastava",
     Content:"It’s a Wednesday, you get up to bring the newspaper inside and you hear seema tai complaining on the phone about how she gets harassed by her husband on the daily. You take matters into your own hands and find out this is a case of domestic violence you look further and see domestic violence in India includes any form of violence suffered by a person from a biological relative, but typically is the violence suffered by a woman by male members of her family or relatives. According to a National Family and Health Survey in 2005, the total lifetime prevalence of domestic violence was 33.5% and 8.5% for sexual violence among women aged 15–49. A survey carried out by the Thomson Reuters Foundation ranked India as the most dangerous country in the world for women."+
     "The perception of women in a patriarchal society is that the involvement of women in household chores is higher than men and the perception of partner involvement is higher in men than women. This creates a barrier between the equality of men and women. The perception of partner involvement increases conflict significantly. This strategically changes the way a family works. When a woman is overpowered in such a way, domestic violence paves commonality. But how common is it in India? The large population of India means that the violence affects 27.5 million women over their lifetimes. The 2012 National Crime Records Bureau report of India states a reported crime rate of 46 per 100,000, a rape rate of 2 per 100,000, a dowry homicide rate of 0.7 per 100,000, and the rate of domestic cruelty by husband or his relatives as 5.9 per 100,000. These reported rates are significantly smaller than the reported intimate partner domestic violence rates in many countries."+ 
     "Domestic violence occurs for a variety of reasons one being the dowry. Dowry payments are another manifestation of the patriarchal structure in India. There are strong links between domestic violence and dowry, a cultural practice deeply rooted in many Indian communities, which is the money, goods, or property the woman/woman’s family brings to a marriage to now become under the ownership of the husband. This practice continues even today in India although banned by law since 1961, and in recent years dowry amounts have risen dramatically."+
     "What can we do to put an end to this and help seema tai?"+
     "A response could be to stop penalizing women for dirty homes. This requires a cultural shift in expectations of “good” womanhood to reduce the cultural pressure of domestic perfection, bringing men into the cleaning process is essential. This means expecting men to be equal housework sharers and not helpers. It also means not penalizing men for “not doing it right” when cleaning. Cleaning the house is a skill men can learn one toilet bowl at a time. And this is the key to reducing gender inequality in housework. Some other ways include:"+
     "• Health: Reducing excess female mortality under five and supporting equal care-seeking behavior for girls and boys."+
     "• Nutrition: Improving the nutrition of women and girls, especially by promoting more equitable eating practices."+
     "• Education: Gender-responsive support to enable out-of-school girls and boys to learn and enabling more gender-responsive curricula and pedagogy (Example: implementing new strategies for identifying vulnerable out of school girls and boys, an overhaul of textbooks so that the language, images, and messages do not perpetuate gender stereotypes)"+
     "• Child protection: Ending child and early marriage (Example: supporting panchayats to become “child-marriage free”, facilitating girls and boys clubs that teach girls sports, photography, journalism, and other non-traditional activities) Social policy: Supporting state governments to develop gender-responsive cash transfer programs and supporting women’s leadership in local governance (Example: cash transfer program in West Bengal to enable girls to stay in school, a Resource Centre for women panchayat leaders in Jharkhand)",
     path:"art5.jpg"
  },
  {
    Title:"A Crash Course on the Horrors of the Internet that Women Face!",
    Authors:"Annanya Srivastava",
    Content:"Gender-based online harassment, sexual or otherwise, stems from the root cause of misogyny, and its underlying social constructs that insist on women’s inferiority to men in every aspect of life. Gender-based hate is simply intended to restore and reinforce the societal differences between women and men. It’s this kind of bigoted mindset that members of GirlUp Athena vow to condemn at every opportunity we get."+
    "As the internet becomes an increasingly important part of human existence and a critical space for marginalized populations to make their voices heard, a woman’s inability to feel safe online impedes her freedom, as well as to her basic human rights. Yet the problem of online violence and harassment is often overlooked in discussions of violence against women. Contrary to the claims that cyberhate is innocuous as compared to physical violence, the long-lasting psychological troubles are evidence enough for the widespread, substantial suffering that women face as a result of online harassment."+
    "Studies conducted by Stanford University have suggested that up to 73 percent of women have been exposed to or have experienced some form of online violence through various social media platforms such as Facebook, Instagram, Twitter, Whatsapp, and TikTok. The sheer volume of cyber harassment may have severe social and economic implications for womens’ status on the internet alongside chilling effects on free speech and advocacy. Harassment of young women directed in different manners- ranging from threats of sexual violence to racist slurs to cyberstalking. It was also observed that members of the LGBTQIA+ community, particularly people who identify as women (both transgendered and cis-gendered), gender non-conforming, non-binary, and gender-fluid, significantly face more abuse and forms of hate speech."+
    "The WWW Foundation has found that law enforcement agencies and the courts are failing to take appropriate actions for cyber harassment against women in 74% of 86 countries surveyed. One in five female Internet users lives in a country where harassment and abuse of women online are extremely unlikely to be punished (source: The Web Index). A report from India suggests that only 35% of women in that country have reported their victimization. Women often prefer not to report cyberhate for the fear of social repercussions."+
    "Women aged 18 to 24 are at a heightened risk of being exposed to every kind of cyberhate; they are uniquely likely to experience stalking and sexual harassment, while also not escaping the high rates of other types of harassment common to young people in general, like physical threats. Studies have shown that 18 percent of women around the globe have experienced a form of serious Internet violence at ages as young as 15. This corresponds to about 9 million women. Women are simply not safe- not online, nor in real life and this fact should make us very angry."+
    "It is to be noted that we understand that men too face online harassment and we are in no way disregarding that. Research has shown that while women face more explicit threats to sexual violence, men face name-calling and threats to physical violence. This is awful and we, in no shape or form, condone such behaviors. We believe that the internet should be a safe space for all kinds of people to express themselves and we stand in solidarity with all people who’ve faced any variation of cyberhate. Rigorous oversight and enforcement of rules banning cyber hate crimes on the Internet is going to be an essential foundation for it to become a safe, respectful, and empowering space for women and girls, and by extension, for boys and men."+
    "Digital security is the protection of someone’s identity online. Gender digital security includes training women to protect themselves, as they are the most significantly vulnerable group of people online.Some tools and tips can help people be safe. For example, Instagram has recently added a “Restrict’ anti-bullying tool that allows users to restrict what some people see on your profile. Instagram also has a tool that allows its users to block their choice of words which is especially helpful in blocking out any form of hate speech."+
    "Professionals in the field of cyber harassment have adopted a three-step plan as a response to any cyberhate one might receive; screenshot-block-report. Following this plan, one is to screenshot any sort of harassment they are receiving, block the sender, and report the issue to the rightful authorities."+
    "According to a recent report published by the United Nations Broadband Commission for Digital Development, their key recommendations are based on the three ‘S’s- Sensitization, Safeguards, and Sanctions’."+
    "• Preventative measures through public sensitization. Changing social attitudes and norms is the first step to shifting the way online abuse is understood and the seriousness with which it is treated. There is a need for public education and education of enforcement agency staff, such as the police."+
    "• Promotion of safeguards for online safety and equality on the Internet for women and girls. Traditional violence-against-women safety frameworks include women’s shelters, crisis centers, helplines, and education: The digital world also requires safety measures to keep up with a rapidly evolving Internet. This will necessarily require resources, attention, and active participation of digital gatekeepers in industry, civil society, and governments."+
    "• Putting in place and enforcement of sanctions through courts and legal systems to define and enforce compliance and effective punitive consequences for perpetrators."+
    "• Each of these pillars of sensitization, safeguards, and sanctions supports the other pillars and will need consistent, collaborative action at many levels."+
    "We also believe that besides these actions, one of the most important things to keep in mind is accountability. People must take accountability for their actions rather than hide under the veil of anonymity that the internet provides. Some things that you can do are-"+
    "• Spread awareness. Any form of hate speech can have long-lasting results on a person’s mental health."+
    "• Hold your friends accountable. To be silent is to be complicit. We want to believe that there are good people out there in the world so do your part with due diligence and call out your friends."+
    "• If someone tells you that you’ve said something wrong- don’t argue. If a woman tells you that your words were hurtful, it is in everyone’s best interest that you accept your mistakes, apologize, and strive to be better and not repeat your actions."+
    "• Keep learning. Educate yourself. Above all, be kind."+
    "Playing our part in raising awareness about this issue, we at GirlUp Athena are participating in the#UltraStopsAtNothing movement, a collaborative campaign by GirlUp India and OnePlus Student Ambassador program. Stay tuned to our social media for more.",
    path:"art6.jpg"
  },
  {
   Title:"O Ri Chiraiya, Angana mein phir aaja re… The Sad Reality of Female Foeticide",
   Authors:"Kuhu Kulkarni and Shakti Tripathi",  
   path:"art7.jpg",
   Content:"Humne tujhpe hazaaro sitham hai kiye"+
   "Humne tujhpe jahaa bhar ke zulm kiye"+
   "Humne socha nahi, Tu jo udh jaayegi"+
   "Ye zameen tere bin sooni reh jaayegi"+
   "Kiske dum pe sajega mera angana"+
   "O Ri Chiraiya, Nanhi si chidiya"+
   "Angana mein phir aaja re…"+
   
   "O Ri Chiraiya, a song from the soundtrack of Satyameva Jayate, composed by Ram Sampath and lyrics by Swanand Kirkire."+
   "Today, 11th October, is The International Day of the Girl Child. On this occasion, we would like to talk about something that has plagued humanity for many years and still does: Female Foeticide, or the destruction or abortion of a female fetus."+
   "It’s a more significant problem than we realize. The sex ratio at birth is naturally considered to be 105 males for every 100 females, but many countries have a skewed sex ration at birth. Sadly, India is no exception. According to the data from the Asian Center for Human Rights, there are 112 males for every 100 females in India. In fact, the problem of foeticide is much deeper than numbers."+
   "With the fast-paced technological advancements in the world, it is now possible to detect the gender of a fetus in the early stages of pregnancy. This has turned out to be the main reason for this skewed sex ratio. We could say that female foeticide is the most initial stage of gender discrimination as the sole reason for foeticide is that the fetus is a girl."+
   "According to an official report by the Indian health ministry in 2013, preference towards a son and female foeticide, along with neglect of the girl child were the primary reasons for the higher mortality rate of girls at a younger age, and for the imbalanced sex ratio in India."+
   "With a population as large as India, even a few percentages of people believing that girls are burdensome to the family can make a huge difference."+
   "• The dowry system,"+
   "• or mindsets like “बेटी पराया धन होती है”,"+
   "• men carry forward the family name and legacy and women don’t; are a few reasons for the gender preference in India leading to female foeticide."+
   "In India, between 1990 and 2018, approximately 15.8 million girls went missing due to prenatal sex selection. The imbalance in sex ratio has also been related to violence towards women."+
   "A study by Sunita Bose and colleagues using the data from National Family Health Survey says that married women living in communities with low sex ratios are significantly more likely to have experienced physical violence from their husbands."+
   "The government has been taking steps to overcome this problem of foeticide and prenatal sex selection by implementing girl child protection schemes around the country. These include: –"+
   "• Beti Bachao, Beti Padhao"+
   "o The Beti Bachao, Beti Padhao (BBBP) project has seen an improvement in the sex ratio in target districts in phase 1 and phase 2 of the project, which is excellent news!"+
   "• Sukanya Samriddhi Yojana which is a special savings scheme for daughters"+
   "• Many states have also implemented such schemes as the Bhagyalakshmi scheme in Karnataka and Majhi Kanya Bhagyashree scheme in Maharashtra."+
  "The literacy rate of girls is also less in India due to gender preferences. Violence is faced by females, not only in India but around the world simply because of their gender."+
   "These problems will keep increasing unless we all come together and do what we can, however small or big, to reduce the cases of foeticide till there are none."+
   "• The smallest acts like talking to people, showing them how foeticide and gender discrimination are wrong,"+
   "• letting a victim know you’re there to help them, supporting them in standing up for themselves or contacting authorities,"+
   "• reporting cases of violence or illegal foeticide that you might come across,"+
   "• educating not just the next generation, but also our parents and grandparents can all help in dealing with these issues."+
   "Here are some helplines working towards children and women’s security: –"+
   "1. Child Line-1098 (https://www.childlineindia.org)"+
   "2. National Repository Of Information For Women (A list of women helplines across states)-http://nari.nic.in/women-helplines-across-state"
  },
  {
     Title:"Even in 2020, Women are Not Safe: Statistics that are Truly Sad.",
     Authors:"Shakti Tripathi and Glynisann Santiago",
     path:"art8.jpg",
     Content:"Empirical evidence shows that globally, 7 percent of women have been sexually assaulted by someone other than a partner and as many as 38 percent of murders of women are committed by an intimate partner. This heart breaking, truly disturbing statistic simply highlights the harsh truth : women around the globe are simply not safe."+ 
     "The National Family Health Survey (NFHS-4) suggests that 30 percent of women in India in the age group of 15-49 have experienced physical violence since the age of 15. But this doesn’t mean that if a girl is below 15 she is safe. In fact in recent news a 2 day old baby was found brutally and mercilessly stabbed to death with a screwdriver, wrapped in a shawl and dumped beside a temple. Makes you really wonder how could someone be so heartless."+
     "The violence towards infants doesn’t stop there, modern medical technology has allowed for the sex of a child to be determined while the child is still a fetus. This allows families to decide if they would like to abort based on sex and female foeticide has been a major concern in this country for years. One study found that 7,997 of 8,000 abortions were of female fetuses. In order to prevent female foeticide, the Preconception and Prenatal Diagnostic Techniques Act of 1994 (PCPNDT Act 1994) was modified in 2003 so as to target medical professionals, but the Act has proven ineffective due to the lack of implementation."+ 
     "The NFHS-4 report further reveals that 6 percent women in the same age group have experienced sexual violence at least once in their lifetime. About 31 percent of married women have experienced physical, sexual or emotional violence by their spouses. India is one of fifty countries that have not yet outlawed marital rape and 20% of Indian men admit to forcing their wives or partners to have sex."+ 
     "Dowry is illegal in India, but despite that it is still a common practice to give expensive gifts to the groom and his relatives at weddings which are hosted by the family of the bride and even though incidents of dowry deaths have decreased 4.5% from 2011 to 2012, still as many as 5,000 dowry deaths are recorded each year."+ 
    "Domestic violence against women is the top gender-related crime, while there has been a marginal increase in rapes as well as overall crime in the country, according to data released by the National Crime Records Bureau (NCRB) for 2018."+
    "India’s average rate of reported rape cases is about 6.3 per 100,000 of the population. Unfortunately these statistics include only reported rape cases and many girls are afraid to speak up. According to a recent report by Livemint, about 99 percent cases of sexual violence go unreported. The extent of under-reporting tends to be higher on average in states with a low female literacy. In all, 3,78,277 cases of crimes against women were reported across the country in 2018, which was an increase in cases compared to previous years. India Today Data Intelligence Unit (DIU) has found that between 2014 and 2018 there have been 1,483 victims of acid attacks in the country."+ 
    "From 2011 to 2012, there was a 26.3% decrease in girls imported to India from another country, but during that time there was a 5.3% increase in violations of the Suppression of Immoral Traffic in Women and Girls Act (SITA). Honor killings have notably increased in some Indian states which has led to the Supreme Court of India, in June 2010, issuing notices to both the Indian central government and six states to take preventative measures against honor killings. The most prominent areas where honor killings occur in India are northern regions."+ 
    "Ranging from the so-called eve teasing and outright sexual harassment on the street or workplace, to harassment for dowry, molestation in public transport vehicles, and the often-reported rape, these crimes against women reflect the vulnerability and deep-rooted problems related to the position of women in Indian society. According to the NCRB, 24,923 cases of rape were reported in 2012, amounting to one rape every 22 minutes."+
    "Gender-based violence, especially violent crime like rape, is a multifaceted problem. Although the incorporation of stricter laws and punishments are important to deter people from committing such crimes, the solution to this is much more than just promulgation."+ 
    "It is very important to tackle various other issues that act as contributing factors and thus play an equally important role, such as the portrayal of women in Indian media, especially cinema. This bears evidence to the deep-rooted prejudicial attitudes towards women and other deeper societal issues that are contributory to these crimes."+
    "Introducing sex education and making it compulsory would also make a big difference."+
    "More campaigns that raise Awareness about rape and violence against women should be introduced so as to empower, help and support women."+
    "But while education and woman empowerment is important, in a country that has so many issues with gender discrimination, bringing about the needed change requires dedicated and combined efforts of multiple agencies such as doctors, nurses and other healthcare providers, researchers and public health professionals too."+
    "We at GirlUp Athena hope to empower as many women as we can and help them escape their bad living conditions, as well as erase the very mental block that makes men believe that they own women. Join us in our fight!"

  },
  {
     Title:"PCOD/PCOS",
     Authors:"Dea Parakh and Tanvi Panse",
     path:"art9.png",
     Content:"I wasn’t having regular cycles…"+
     "I’ve been overweight my entire life, and I need a change…"+
  
     "The female body undergoes a lot of ups and downs in the course of a lifetime. We’ve all heard these statements from at least one of our girlfriends."+
     "Polycystic Ovary Disease and Polycystic Ovary Syndrome are two conditions where the female body undergoes various transformations. These transformations don’t just have a physical outline to them, but also cause adverse emotional distresses to the individual."+
     "So let’s break it down."+
     "What It Really Is"+
     "PCOD, or Polycystic Ovary Disease, is a kind of hormonal disorder that affects one in 10 women. It refers to a condition when a woman has a number of small cysts in the ovaries. Besides unpredictable hormonal behaviour, this condition can trigger diabetes, infertility, acne and excessive hair growth. It is a very common condition affecting 5% to 10% of women in the age group 12–45 years, due to hormonal imbalance. It can cause problems with menstruation, making it difficult for the individual to conceive."+
"Normally, the ovaries make female sex hormones and a tiny amount of male sex hormones. These help to regulate the normal development of eggs in the ovaries during each menstrual cycle."+
"Polycystic Ovary Syndrome is related to an imbalance in these sex hormones. In PCOS, they start making a higher amount of male sex hormones. This causes patients to stop ovulating."+
"Normally, one or more eggs are released during each menstrual cycle from sacs in the ovaries, the process of which is called ovulation. In polycystic ovary syndrome, the eggs in these follicles do not mature and are not released from the ovaries. Instead, they form very small cysts in the ovary, and hence the name “polycystic ovaries”. PCOS seems to run in families, so the chance of having it is higher if other women in the family have PCOS or irregular periods."+
"Body Issues"+
"The hormonal imbalance and increase in male sex hormones create a prominent change in the individual’s body. These can include:"+
"•Acne"+
"•Weight gain and trouble losing weight."+
"•An increase in facial and body hair, with thinning of scalp hair."+
"•Irregular periods. Often women with PCOS have fewer than nine periods a year. Some women have no periods, whereas some experience very heavy bleeding."+
"•Fertility problems. Many women who have PCOS have trouble getting pregnant. •Infertility is a major symptom of PCOS."+
"•Depression and aggressive mood swings."+
"•Premature deliveries."+
"•Diabetes."+
"•High blood pressure."+
"Although PCOD and PCOS are conditions that don’t have an accurate cure, they can both be treated to improve fertility and control blood sugar or blood pressure levels. Treatments to control acne are very common among patients suffering from PCOD or PCOS. Intake of extra hormones externally provides control towards excessive hormonal imbalance. Such treatments help to improve the overall condition and contain aggressive symptoms; however, a specific cure is still underway. Something we’re sure everyone is desperate to see."+
"Scars and Humiliation (How women feel due to the physical manifestations of the disease)"+
"These conditions affect the image a girl in t@girlupathena hese times, so desperately craves to have, very drastically. The changes in her appearance lead to embarrassment, and reduced confidence. Anxiety and hysteria gets to her, emotionally affecting the mood, not just hormonally anymore, but out of humiliation."+
"We know that everybody, is beautiful in their own ways. The imperfections are what make them you, unique. The societal standards we impose do no help to anyone. The constant pressure can push these girls towards severe depression in trying to achieve something that is totally out of their control, and this is what is absolutely shameful, immoral and disgraceful for us to know as a community."+
"Upon reading countless articles while doing my research, the stories some girls had to tell, were absolute disheartening. Thousands of rupees are spent on hair removal and acne treatments; some go to the extent of surgically getting their bodies restructured; and all of this, JUST to fit in. But why create this pressure? Are we not womanly enough with a little more hair, a cheekier frame or a few more scars? Who decides these rules? There is no need for us all to look like clones of a decided standard because there really isn’t one."+
"So let’s make it an emotionally safer environment for those around us and scrap away this toxic female ideology of a “feminine” body, and lets live to empower each other."

  },
 
  {
    Title:"Our Monthly Menstrual Cycle- Let’s talk about it!",
    Authors:"Shakti Tripathi and Glynisann Santiago",
    path:"art11.jpg",
    Content:"Shh! Don’t talk about it, it’s not good, no one needs to know. This is something that most young girls are told as soon as they get their first period."+
    "The most ironic part of this all is that we as a society jump in to tell girls how to live like a girl, what not to talk about, but never volunteer to have an open conversation about a natural bodily function that happens monthly. EVERYBODY should know about it. We at Girl Up Athena want to open this conversation."+
    "Let’s talk about periods!"+
    "An important thing to remember, before we dive in, is that not everyone who menstruates in a woman, and not every woman menstruates. There are trans boys, and well as non-binary individuals who get their periods, and this is something we should normalise. Hence, from this point on, we shall use the gender neutral pronouns (they/them) while talking about periods."+
    "What is a menstrual cycle? Simply put, it is the monthly hormonal cycle that a body goes through to prepare for pregnancy."+
    "Every month, the body prepares itself for pregnancy. This includes the thickening of the lining of the uterus and the production of ‘oocytes’ (a gametocyte or germ cell involved in reproduction). The egg is released from an ovary around day fourteen in the cycle; and the thickened lining of the uterus provides nutrients to the embryo in case of ‘implantation’. In case the person is not pregnant, the lining is released through the vagina, which is commonly known as a period."+
    "Hormone levels (estrogen and progesterone) usually change throughout the cycle and can cause a myriad of symptoms. These symptoms include abdominal and pelvic cramping, lower back pain, bloating and sore breasts, food cravings, mood swings and irritability, headache, fatigue, etcetera."+
    "Young people usually get their first period between the age of 8 to 15 years. Cycles may change in different ways as a girl grows. In most of the cases, periods are heavier for teenagers but gradually get lighter in their 20s and 30s which is completely normal."+
    "For a few years after getting their first period, their cycles’ time duration can go longer than 38 days, which is quite common. The regularity of the cycles is high within the three years after her first period. In her 20s and 30s, cycles are generally regular and can last anywhere from 24 to 38 days. In their 40’s, the body starts the transition to “menopause”."+
    "Menopause is the natural decline of reproductive hormones when a person reaches their 40s or 50s. Cycles in this age generally become irregular and menstrual periods might stop for a month or a few months and then start again. They also might be shorter or last longer than usual or be lighter or heavier than normal."+
    "There are times when the changes do not occur as expected or there are some drastic changes that can be of concern. Sometimes, a child’s periods start before they are 8, and they develop breasts early. This can be an isolating experience. Or for some children, their periods don’t start even after they have turned 15, which is equally embarrassing. Some people have highly irregular cycles, some have excessive pain and bleeding, to an extent that they miss regular activities. It is important to consult a doctor, instead of ignoring it or taking medication at your discretion."+
    "As a person grows older, they experiences changes, some of which are quite difficult to understand at a young age. Hence an adult needs to explain the entire process frankly, at a young age, so one can be prepared. Young people need to understand that periods are natural, and not something to be embarrassed about and hide. They should be the changes their body will go through, and to plan for them."+
    "Planning involves keeping track of their period, the regularity of the periods which in turn will help them to know when they ovulate, which is when they are most likely to get pregnant, and when to expect their next period. This planning can also help in tracking problems that can be discussed with a doctor. There are many applications (on both android and apple) that help you track your periods and ovulation."+
    "Previous generations have been raised to believe that people must be isolated while on their periods. In many households, a person on their period is told to avoid going anywhere, not tell anyone about what is happening, and is isolated. A lot of men and women still consider periods and blood disgusting. We don’t seem to acknowledge that this process is a part of the magical process of bringing life on Earth, it is something to be cherished. Let us work together to educate everyone, and help them understand what exactly periods are, and why we must talk about them."
    
    


  },
  {
     Title:"Contraception and Menstrual Cups:Answering Questions You Might Have",
     Authors:"Annanya Srivastava and Glynisann Santiago",
     path:"art9.jpg",
     Content:"Contraception can truly be considered one of modern medicine’s greatest advances and yet, it is still one of the least talked about topics, especially in India. Talking about safer sex practices or giving any indication of the intention of performing sexual activities with your partner tends to stir up feelings of shame in many communities around the globe, including India. This is exactly the sort of taboo barrier that GirlUp Athena pledges to purge."+
     "What Exactly is Contraception?"+
     "Contraception, also known as birth control, is the use of various devices, drugs, agents, sexual practices, or surgical procedures to prevent conception or pregnancy."+
     "Birth control methods can be broadly classified into:"+
     "•barrier methods,"+
     "•methods that prevent ovulation such as the birth control pill,"+
     "•and methods that allow fertilization of the egg but prevent implantation of the fertilized egg inside the uterus (womb)."+
     "In simpleton words, contraceptives not only enable people to choose when they want to have a baby, but various forms of birth control options also prevent them from acquiring or spreading sexually transmitted diseases (such as HIV, Chlamydia, HPV, etc.) Couples who do not use any method of contraception have an approximately an 85% chance of experiencing pregnancy over a year."+
     "How Do I Choose the Ideal Contraceptive for ME?"+
     "Well, for starters, the decision about what kind of birth control option to use is extremely personal, and there is no single choice that is safest or best for all people. The risks and benefits should actively and carefully be weighed, along with the effectiveness of each technique before choosing a birth control method."+
     "The contraceptive pill, for example, when used correctly, is over 99 percent effective. However, because people make mistakes, as many as 9 women each year will become pregnant while using it. Your choice of birth control should depend on several factors. These include your health, frequency of sexual activity, number of sexual partners, and desire to have children in the future. A thorough and open discussion with a health care professional is the best option for making a safe and informed decision."+
     "We find that it is important to note that contraceptives are not only effective and important in the reproductive health of heterosexual partners, but also extremely pivotal in the sexual health of same-sex couples or couples that may have gender non-conforming partners to prevent the acquisition or spread of sexually transmitted diseases."+
     "Making a safe and informed decision can often be considered rather challenging so we’re here to break down all the facts for you!"

  },
  {
   Title:"Myths, Well they need to be Busted!",
   Authors:"Kuhu Kulkarni and Tanvi Panse",
   path:"art10.jpg",
   Content:"For most of us, periods come every month. Cramps and bleeding for 3 to 8 days, food cravings, mood swings; that is all that most people seem to know about periods, but there is so much more to it than that."+

   "A week or so before their period, 3 out of 4 people* go through Premenstrual Syndrome (PMS), and it lasts till the beginning of periods. PMS has symptoms such as mood swings, fatigue, food cravings, sore breasts, irritability, and depression. It is caused due to the cyclic changes in hormone levels, chemical changes in the brain as well as depression, but can largely be controlled through lifestyle changes and treatments."+
   
   "There are many myths and misconceptions about periods and PMS, and when there are myths, they need to be busted! Here are some of these myths, and what is the truth behind them: –"+
   
   "Myth #1: Not everyone who gets their period is a woman, and not every woman gets their period."+
   "There are trans boys, non- binary and well as gender fluid individuals who get their periods because of the sexual organs they were born with. It. Is important to acknowledge them as well. And every woman does not get her period. In a condition called amenorrhea, a woman either doesn’t get her period by the age of 16, or stops getting her monthly cycle for 3 or more months. More often than not, this is treatable."+
   "Myth #2: One loses a lot of blood during periods."+
"The truth is that people usually lose around two to three tablespoons of blood during their period, and if someone experiences heavy periods, also known as menorrhagia, they lose about four tablespoons of blood."+
"Some may lose more blood, but if it starts affecting your daily life, or if you’re bleeding for more than seven days, or becoming anemic, please visit a doctor. Heavy bleeding is not normal or healthy, and most people do not lose too much blood during their period."+

"Myth #3: You can’t get pregnant while you’re on your period."+
"This is true, but there’s a catch, sperm can live inside your body for five days. Hence, it’s likely that sperm can stay alive through the period, making it possible to get pregnant despite being on your period or having crossed your ovulation. So, a condom is always a must if you aren’t ready to commit to taking care of a baby yet, of course, it always helps to be protected from STDs (Sexually Transmitted Diseases.)"+

"Myth #4: Period pain is like any other pain you experience."+
"Ah, we wish. But this couldn’t be further from the truth. Period pain is different from any other pain you have experienced, ask anyone who menstruates, and they’ll tell you the same. Period pain can interfere with work and life; it even has a medical name- dysmenorrhea, a quiet mouthful, right? Well, common dysmenorrhea is the term for common period cramps that people experience, which are mostly pretty painful, and as if all of this wasn’t enough, period cramps can also affect the person’s ability to concentrate and make them feel more anxious."+
"Myth #5: It would be best if you do not exercise during your period."+
"This is probably something your mom or an auntie has told you before, mine sure has, but the truth is, this is entirely false. Instead, regular exercise goes a long way in helping with period cramps and releasing emotional stress, and it does not have to stop during your period! Exercise can reduce any feelings of fatigue you might be feeling during your period. It also releases endorphins and dopamine that help relieve stress and make you feel better and happier."+

"Myth #6: Mood swings and food cravings are the only symptoms of PMS."+
"Mood swings and food cravings are indeed a symptom of PMS, but they’re not the only symptoms. PMS includes many more symptoms like headache, fatigue, irritability, tender breasts, abdominal bloating, constipation, nausea, loss of appetite or excessive hunger, and lack of concentration. Some also experience anxiety and depressed mood, crying spells, and breast, abdomen, back or muscle pain, or even pelvis pain."+
"Myth #7: Everyone experiences PMS symptoms."+
"Most people experience some PMS symptoms in their life. It is estimated that 3 out of 4 menstruating people experience some form of PMS, but mostly, they are mild. Just like the pain during periods varies from person to person, the symptoms and intensity of PMS also vary."+
"For those who do experience intense symptoms, going through it is not the easiest of tasks. Mostly, the symptoms are in a predictable pattern, but the emotional stress and physical pain can interfere with daily life."+
"Imagine everything is going right, but then suddenly you don’t feel like yourself. You are enjoying yourself with your friends and family but then suddenly your mood shifts, and you feel irritated or angry, and you don’t understand why? That’s PMS."+

"Myth #8: You can’t go swimming while on your period."+
"No swimming while on your period is now in the past, with tampons and menstrual cups available, going swimming while on your period is not a problem anymore. But yes, do be careful about the tampons you use as some might have harmful chemicals."+
"Myth #9: Your period stops when you get in the water."+
"Your period doesn’t stop when you get in the water, the period blood flow may temporarily slow down as the gravitational pull isn’t as strong in the water, but the flow doesn’t stop altogether."+

"Myth #10: You have to live with PMS."+
"While there is no way of getting away from PMS symptoms, but there are ways to reduce their intensity. Some lifestyle changes, like being aware of what you eat, regular exercise, and meditation, can help you deal with PMS symptoms better. Cognitive-behavioral therapy (CBT) and some medication are also available to help you deal better with PMS."+

"Myth #11: Period blood is unclean."+
"Period discharge is made of blood, tissue from the uterus, and mucus, and it’s not much different from the blood that runs through your veins so no, period blood is not unclean and nor is a menstruating person."+
"PMS and periods are very natural and should not be a taboo subject, there’s nothing to be ashamed of when talking about them. Everybody needs to be aware of what PMS and periods are like."+
"So, let us all do our part in educating ourselves and others and put an end to the stigma attached to period talk."+

"*As mentioned in the article, there are trans boys, gender-fluid, and well as non-binary individuals who get their periods, and this is something we should normalize. Hence, we use the gender-neutral terminology and pronouns (they/them) while talking about periods."

  }


];

export default articles;
